CREATE TABLE price_schedule (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    sku_id BIGINT NOT NULL,
    merchant_id BIGINT NOT NULL,
    target_price_json JSON NOT NULL,
    effective_at DATETIME NOT NULL,
    expire_at DATETIME NULL,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
