package com.example.ecommerce.shared.api;

public enum ErrorCode {
    SUCCESS,
    COMMON_VALIDATION_FAILED,
    COMMON_VERSION_CONFLICT,
    AUTH_MERCHANT_SCOPE_DENIED,
    PRODUCT_NOT_FOUND,
    SKU_SPEC_DUPLICATED,
    INVENTORY_INSUFFICIENT,
    PRICE_SALE_GREATER_THAN_LIST
}
