package com.example.ecommerce.shared.api;

public enum ErrorCode {
    SUCCESS,
    COMMON_VALIDATION_FAILED,
    COMMON_INTERNAL_ERROR,
    COMMON_VERSION_CONFLICT,
    AUTH_UNAUTHENTICATED,
    AUTH_INVALID_CREDENTIALS,
    AUTH_INVALID_ROLE,
    AUTH_MERCHANT_SCOPE_DENIED,
    PRODUCT_NOT_FOUND,
    SKU_SPEC_DUPLICATED,
    INVENTORY_INSUFFICIENT,
    INVENTORY_VERSION_CONFLICT,
    PRICE_SALE_GREATER_THAN_LIST,
    PRICE_SCHEDULE_CONFLICT
}
